TolabPortal/TolabPortal/Models/RegisterSection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TolabPortal.Models
{
    public class RegisterSection
    {

        public string Section { get; set; }
    }
}

TolabPortal/TolabPortal/Controllers/InterestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Tolab.Common;
using TolabPortal.DataAccess.Models;
using TolabPortal.DataAccess.Services;
using TolabPortal.Models;

namespace TolabPortal.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class InterestController : Controller
    {
        private readonly IInterestService _interestService;
        private readonly ISessionManager _sessionManager;
        private readonly IAccountService _accountService;

        public InterestController(IInterestService interestService,
            ISessionManager sessionManager,
            IAccountService accountService)
        {
            _interestService = interestService;
            _sessionManager = sessionManager;
            _accountService = accountService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("RegisterSection")]
        public async Task<IActionResult> RegisterSection(string errorMessage)
        {
            ViewBag.ErrorMessage = errorMessage;

            var sectionsResponse = await _interestService.GetSections();

            if (sectionsResponse.IsSuccessStatusCode)
            {
                var responseResult = await CommonUtilities.GetResponseModelFromJson<SectionResponse>(sectionsResponse);
                return View("RegisterSection", responseResult);
            }

            return View("RegisterSection");
        }

        [HttpPost]
        [Route("RegisterSection")]
        public async Task<IActionResult> RegisterSection(SectionResponse sectionResponse, string sectionId)
        {
            if (sectionId != null)
            {
                var sectionCategoriesResponse = await _interestService.GetCategoriesBySectionId(long.Parse(sectionId));
                if (sectionCategoriesResponse.IsSuccessStatusCode)
                {
                    var selectedSection = sectionResponse.Sections.FirstOrDefault(s => s.Id == long.Parse(sectionId));
                    var responseResult = await CommonUtilities.GetResponseModelFromJson<CategoryResponse>(sectionCategoriesResponse);
                    responseResult.SelectedSection = selectedSection;
                    return View("RegisterCategory", responseResult);
                }
                else
                {
                    var responseResult = await CommonUtilities.GetResponseModelFromJson<CategoryResponse>(sectionCategoriesResponse);
                    var errorMessage = responseResult.Errors.Message;
                    return RedirectToAction("RegisterSection", new { errorMessage = errorMessage });
                }
            }
            else
            {
                var errorMessage = "لم يتم اختيار مرحلة";
                return RedirectToAction("RegisterSection", new { errorMessage = errorMessage });
            }
        }

        [Route("RegisterCategory")]
        public IActionResult RegisterCategory(string errorMessage)
        {
            ViewBag.errorMessage = errorMessage;
            return View("RegisterCategory");
        }

        [HttpPost]
        [Route("RegisterCategory")]
        public async Task<IActionResult> RegisterCategory(CategoryResponse categoryResponse, string categoryId)
        {
            if (categoryId != null)
            {
                var subCategoriesResponse = await _interestService.GetSubCategoriesByCategoryId(long.Parse(categoryId));
                if (subCategoriesResponse.IsSuccessStatusCode)
                {
                    var selectedCategory = categoryResponse.Categories.FirstOrDefault(s => s.Id == long.Parse(categoryId));
                    var responseResult = await CommonUtilities.GetResponseModelFromJson<SubCategoryResponse>(subCategoriesResponse);

                    // getting departments for each sub category
                    for (int i = 0; i < responseResult.SubCategories.Count; ++i)
                    {
                        var subCategory = responseResult.SubCategories[i];
                        var departmenResponse = await _interestService.GetDepartmentsBySubCategoryId(subCategory.Id);
                        var departments = await CommonUtilities.GetResponseModelFromJson<DepartmentResponse>(departmenResponse);
                        responseResult.SubCategories[i].Departments = departments.Departments;

                        responseResult.SubCategories[i].Name = responseResult.SubCategories[i].Name.Replace("\t", "");
                        responseResult.SubCategories[i].NameLT = responseResult.SubCategories[i].NameLT.Replace("\t", "");
                    }
                    responseResult.SelectedCategory = selectedCategory;
                    return View("RegisterSubCategory", responseResult);
                }
                else
                {
                    var responseResult = await CommonUtilities.GetResponseModelFromJson<CategoryResponse>(subCategoriesResponse);
                    var errorMessage = responseResult.Errors.Message;
                    return RedirectToAction("RegisterCategory", new { errorMessage = errorMessage });
                }
            }
            else
            {
                var errorMessage = "لم يتم اختيار مرحلة";
                return RedirectToAction("RegisterCategory", new { errorMessage = errorMessage });
            }
        }

        [Route("RegisterSubCategory")]
        public IActionResult RegisterSubCategory(string errorMessage)
        {
            ViewBag.errorMessage = errorMessage;
            return View("RegisterSubCategory");
        }

        [HttpPost]
        [Route("RegisterSubCategory")]
        public async Task<IActionResult> RegisterSubCategory(long[] departmentIds)
        {
            if (departmentIds == null || departmentIds.Length == 0)
            {
                var errorMessage = "لم يتم اختيار مرحلة";
                return RedirectToAction("RegisterSubCategory", new { errorMessage = errorMessage });
            }

            var redirectToMyProfile = false;
            var studentProfileResponse = await _accountService.GetStudentProfile();
            var studentProfile = await CommonUtilities.GetResponseModelFromJson<GetStudentProfileModel>(studentProfileResponse);
            if (studentProfile.model.Interests.Any())
                redirectToMyProfile = true;

            var subCategoriesResponse = await _interestService.AddDepartmentToStudent(departmentIds.ToList());

            if (redirectToMyProfile)
                return RedirectToAction("EditProfile", "Home");

            return RedirectToAction("HomeCoursesNew", "Subjects");
        }

        [Route("RegisterDepartment")]
        public IActionResult RegisterDepartment()
        {
            return View();
        }

        [HttpPost]
        [Route("RegisterDepartment")]
        public async Task<IActionResult> RegisterDepartment(string subCategoryId)
        {
            return View();
        }

        private async Task<IEnumerable<Claim>> GetUserClaims()
        {
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, User.FindFirstValue(ClaimTypes.NameIdentifier)),
                new Claim("AccessToken", User.FindFirstValue("AccessToken")),
                new Claim("CountryId", User.FindFirstValue("CountryId")),
                new Claim("CountryCode", User.FindFirstValue("CountryCode")),
                new Claim("UserPhoto", User.FindFirstValue("UserPhoto")),
                new Claim("HasInterests", true.ToString()),
                new Claim("Email", User.FindFirstValue("Email")),
                new Claim("Phone", User.FindFirstValue("Phone")),
                new Claim("IdentityId", User.FindFirstValue("IdentityId")),

            };

            return claims;
        }
    }
}

TolabPortal/TolabPortal/Views/Interest/RegisterCategory.cshtml
@model TolabPortal.DataAccess.Models.CategoryResponse

@{
    ViewBag.CurrentPageTitle = "اختر المرحلة";
    var items = new string[] { "الرئيسية", "اختر المرحلة" };
    ViewBag.MenuItems = items;
}
<div class="col-lg-7 mx-auto">


    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger2 alert-dismissible fade show course-alert-info">
            <div class="d-flex align-items-center">
                <i class="la la-info-circle fs-30 mr-2"></i> @ViewBag.ErrorMessage
            </div>
            <button type="button" class="close fs-20 pd-16" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" class="la la-times"></span>
            </button>
        </div>
    }

    <div class="card card-item">
        <div class="card-body">
            <form class="pt-2" method="post" asp-action="RegisterCategory" asp-controller="Interest">
                <p class="mb-4 fontbb">@(Model.SelectedSection.NameLT)</p>
                <div class="row">
                    @if (Model?.Categories != null)
                    {
                        for (int i = 0; i < Model.Categories.ToList().Count; i++)
                        {
                            var category = Model.Categories[i];
                            <div class="col-lg-12 responsive-column-half">
                                <div class="custom-control custom-radio mb-3 ml-0 pl-0">
                                    <input type="radio" class="custom-control-input" id="@(category.Id)" name="categoryId" value="@(category.Id)">
                                    <label class="custom-control-label custom--control-label custom--control-label-boxed noshadbord" for="@(category.Id)">
                                        <span class="font-weight-semi-bold text-black d-block"> @(category.NameLT) @(category.NameLT.Contains("الكويت") ? $" - {category.SubCategories.FirstOrDefault().NameLT}" : "")</span>
                                    </label>
                                    <input asp-for="Categories[i].Id" value="@(category.Id)" hidden />
                                    <input asp-for="Categories[i].Name" value="@(category.Name)" hidden />
                                    <input asp-for="Categories[i].NameLT" value="@(category.NameLT)" hidden />
                                    <input asp-for="Categories[i].SectionId" value="@(category.SectionId)" hidden />
                                </div>
                            </div>
                        }
                    }

                </div>
                <div class="btn-box align-items-center justify-content-between mt-2 pullone">
                    <a href="@Url.Action("RegisterSection")" class="btn-text linkunder2">رجوع</a>
                    <button type="submit" class="btn theme-btn ml-3 ">التالي <i class="la la-arrow-right icon ml-1"></i></button>
                </div><!-- end btn-box -->
            </form>
        </div><!-- end card-body -->
    </div><!-- end card -->

</div>

TolabPortal/TolabPortal/Views/Interest/RegisterDepartment.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TolabPortal/TolabPortal/Views/Interest/RegisterSection.cshtml
@using Microsoft.Extensions.Options
@using Tolab.Common
@model TolabPortal.DataAccess.Models.SectionResponse
@inject IOptions<ApplicationConfig> options;

@{
    var config = options.Value;

    ViewBag.CurrentPageTitle = "اختر المرحلة";
    var items = new string[] { "الرئيسية", "اختر المرحلة" };
    ViewBag.MenuItems = items;
}
<div class="col-lg-7 mx-auto">
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger2 alert-dismissible fade show course-alert-info">
            <div class="d-flex align-items-center">
                <i class="la la-info-circle fs-30 mr-2"></i> @ViewBag.ErrorMessage
            </div>
            <button type="button" class="close fs-20 pd-16" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" class="la la-times"></span>
            </button>
        </div>
    }

    <div class="card card-item">
        <div class="card-body">
            <form class="pt-2" method="post" asp-action="RegisterSection" asp-controller="Interest">
                <p class="mb-4">قم بتخصيص حسابك واختيار اهتمامتك</p>
                <div class="row">
                    @if (Model?.Sections != null)
                    {
                        for (int i = 0; i < Model.Sections.ToList().Count; ++i)
                        {
                            var section = Model.Sections[i];
                            <div class="col-lg-12 responsive-column-half">
                                <div class="custom-control custom-radio mb-3 ml-0 pl-0">
                                    <input type="radio" class="custom-control-input" id="@(section.Id)" name="sectionId" value="@(section.Id)">
                                    <label class="custom-control-label custom--control-label custom--control-label-boxed noshadbord" for="@(section.Id)">
                                        <img src="@config.MediaBaseUrl/ws/Images/SectionImages/@(section.Image)" class="chosimg">
                                        <span class="font-weight-semi-bold text-black d-block"> @(section.NameLT) </span>
                                    </label>
                                    <input asp-for="Sections[i].Id" value="@(section.Id)" hidden />
                                    <input asp-for="Sections[i].Name" value="@(section.Name)" hidden />
                                    <input asp-for="Sections[i].NameLT" value="@(section.NameLT)" hidden />
                                </div>
                            </div>
                        }
                    }
                </div>
                <div class="btn-box align-items-center justify-content-between mt-2 pullone">
                    <button type="submit" class="btn theme-btn ml-3 ">التالي <i class="la la-arrow-right icon ml-1"></i></button>
                </div><!-- end btn-box -->
            </form>
        </div><!-- end card-body -->
    </div><!-- end card -->
</div>

TolabPortal/TolabPortal/Views/Interest/RegisterSubCategory.cshtml
@model TolabPortal.DataAccess.Models.SubCategoryResponse

@{
    ViewBag.CurrentPageTitle = "اختر الصف";
    var items = new string[] { "الرئيسية", "اختر الصف" };
    ViewBag.MenuItems = items;
}


<div class="col-lg-7 mx-auto">
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger2 alert-dismissible fade show course-alert-info">
            <div class="d-flex align-items-center">
                <i class="la la-info-circle fs-30 mr-2"></i> @ViewBag.ErrorMessage
            </div>
            <button type="button" class="close fs-20 pd-16" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" class="la la-times"></span>
            </button>
        </div>
    }

    <div class="card card-item">
        <div class="card-body">
            <form class="pt-2" method="post" asp-action="RegisterSubCategory" asp-controller="Interest">
                <p class="mb-4 fontbb"> @Model.SelectedCategory.NameLT </p>
                <div class="payment-option-wrap">
                    @for (int i = 0; i < Model.SubCategories.Count; i++)
                    {
                        <div class="payment-tab noshadbord">
                            @{
                                var subCategory = Model.SubCategories[i];
                            }
                            <div class="payment-tab-toggle">
                                <input type="radio" id="@(subCategory.Id)" name="subCategoryId" value="@(subCategory.Id)">
                                <label for="@(subCategory.Id)">@(subCategory.NameLT)</label>
                            </div>
                            <div class="payment-tab-content">
                                @for (int j = 0; j < subCategory.Departments.Count; ++j)
                                {
                                    var department = subCategory.Departments[j];
                                    <div class="custom-control custom-checkbox fs-15">
                                        <input type="checkbox" class="custom-control-input" id="@(department.Id)" value="@(department.Id)" name="departmentIds">
                                        <label class="custom-control-label custom--control-label w-100" for="@(department.Id)">@department.NameLT</label>
                                    </div>
                                    <!-- end custom-control -->
                                }

                            </div>
                        </div><!-- end payment-tab -->



                    }
                </div>
                <div class="btn-box align-items-center justify-content-between mt-2 pullone">
                    <a href="@Url.Action("RegisterSection")" class="btn-text linkunder2">رجوع</a>
                    <button type="submit" class="btn theme-btn ml-3 ">تخصيص <i class="la la-arrow-right icon ml-1"></i></button>
                </div><!-- end btn-box -->
            </form>
        </div><!-- end card-body -->
    </div><!-- end card -->
</div>

@section Scripts
{
    <script>

        $(function () {
            $('input[type=radio][name=subCategoryId]').change(function () {
                var firstDepartment = $(this).parent().next().children().find('input[type=checkbox][name=departmentIds]').first();

                $('input[type=checkbox]').prop('checked', false).change();

                if (firstDepartment != null) {
                    $(firstDepartment).prop("checked", true).change();
                }
            });
        });
    </script>
}