TolabPortal/TolabPortal/Controllers/MyFatoorahPaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Tolab.Common;
using TolabPortal.DataAccess.Models.Payment;
using TolabPortal.DataAccess.Services;
using TolabPortal.DataAccess.Services.Payment;
using TolabPortal.ViewModels;

namespace TolabPortal.Controllers
{
    public class MyFatoorahPaymentController : Controller
    {
        private readonly IMyFatoorahPaymentService _paymentService;
        private readonly ISubscribeService _subscribeService;
        private readonly ISessionManager _sessionManager;
        private readonly ILogger<MyFatoorahPaymentController> _logger;
        private readonly ApplicationConfig _config;

        public MyFatoorahPaymentController(IMyFatoorahPaymentService paymentService, ISubscribeService subscribeService,
            ISessionManager sessionManager, ILogger<MyFatoorahPaymentController> logger, IOptions<ApplicationConfig> config)
        {
            _paymentService = paymentService;
            this._subscribeService = subscribeService;
            this._sessionManager = sessionManager;
            this._logger = logger;
            this._config = config.Value;
        }

        // [Route("~/InitiatePayment/{amount}")]
         [HttpPost]
        public async Task<IActionResult> InitiatePayment(PayVm payViewmodel)
        {
            //دفع بالمحفظة
            if (payViewmodel.PaymentMethodId == 1)
            {
                if (payViewmodel.InvoiceAmount >=0)
                {
                    
                    if (payViewmodel.InvoiceAmount >  _sessionManager.WalletAmount)
                    {
                        ViewBag.ErrorMessage = "عذرا الرصيد لا يكفى برجاء شحن المحفظة و المحاولة مرة أخرى";
                        return RedirectToAction("Index","Wallet");
                    }
                    else
                    {
                        var invoiceObj = new PaymentViewModel()
                        {
                            InvoiceValue = payViewmodel.InvoiceAmount,
                            CustomerName = _sessionManager.UserId ?? "",
                            CustomerReference = payViewmodel.TransactionId,
                            TransactionType = payViewmodel.TransactionType
                        };
                         await CompletePayment(payViewmodel.PaymentMethodId.ToString(), true, invoiceObj);
                        ViewBag.SuccessMessage = "تم الاشتراك بنجاح";
                        return RedirectToAction("MyCourses", "Subjects");
                    }
                }
               
                    return View("ErrorPayment");

            }
            //دفع الكترونى
            else
            {
                if (payViewmodel.InvoiceAmount == 0)
                    return RedirectToAction("CompleteFreePayment", new
                    {
                        TransactionType = payViewmodel.TransactionType,
                        tranactionId = payViewmodel.TransactionId,
                        redirectUrl = $"{_config.CallBackPayemntRoot}{payViewmodel.ReturnRoute}"
                    });
                //var response = await _paymentService.InitiatePayment(new InitiatePaymentRequest
                //{
                //    InvoiceAmount = payViewmodel.InvoiceAmount,
                //    CurrencyIso = "kwd"
                //}).ConfigureAwait(false);
                //if (response.IsSuccess)
                //{ 
                List<InitiatePaymentMethodsModel> paymentMethods = new List<InitiatePaymentMethodsModel>();
                paymentMethods.Add(new InitiatePaymentMethodsModel() { CurrencyIso = "KWD", ImageUrl = "https://portal.myfatoorah.com/imgs/payment-methods/kn.png", PaymentMethodAr = "كى نت", TotalAmount = payViewmodel.InvoiceAmount, PaymentMethodId = 1 });
                paymentMethods.Add(new InitiatePaymentMethodsModel() { CurrencyIso = "KWD", ImageUrl = "https://portal.myfatoorah.com/imgs/payment-methods/vm.png",PaymentMethodAr= "فيزا / ماستر",TotalAmount=payViewmodel.InvoiceAmount,PaymentMethodId=2 });
                        return View(new PaymentViewModel()
                    {
                        InvoiceValue = payViewmodel.InvoiceAmount,
                        PaymentMethods = paymentMethods,
                        CustomerName = _sessionManager.UserId ?? "",
                        CustomerReference = payViewmodel.TransactionId,
                        TransactionType = payViewmodel.TransactionType,
                        ReturnUrl = $"{_config.CallBackPayemntRoot}{payViewmodel.ReturnRoute}"
                    });
                //}
              /*  else
                {
                    var errors = "";
                    if (response.ValidationErrors!=null)
                    {
                        foreach (var item in response.ValidationErrors)
                        {
                            errors += $" {item.Name} : {item.Error}   ||||||";
                        }
                    }
                    await _subscribeService.InsertError(payViewmodel.TransactionId,

                        $"Response State is :{response.IsSuccess} ||Errors :{response.ValidationErrors} |||| response Message : {response.Message}");
                    return View("ErrorPayment");

                }*/
            }
        }

        [HttpPost("executePayment")]
        public async Task<IActionResult> ExecutePayment(PaymentViewModel paymentVm)
        {
            if (ModelState.IsValid)
            {


                var response = await _paymentService.ExecutePayment(new ExecutePaymentRequest()
                {
                    PaymentMethodId = paymentVm.PaymentMethodId,
                    InvoiceValue = paymentVm.InvoiceValue == 0 ? 1 : paymentVm.InvoiceValue,
                    CustomerReference = paymentVm.CustomerReference,
                    CustomerName = _sessionManager.UserId ?? "",
                    UserDefinedField = $"{paymentVm.TransactionType},{paymentVm.ReturnUrl},{_sessionManager.IdentityId}",
                    CallBackUrl = $"{_config.CallBackPayemntRoot}/CompletePayment",
                    ErrorUrl = $"{_config.CallBackPayemntRoot}/ErrorPayment",
                    Language = "AR",
                    CustomerMobile= _sessionManager.CountryCode+_sessionManager.Phone,
                    CustomerEmail=_sessionManager.Email,
                    ExpiryDate = DateTime.Now.AddYears(1),
                 
                }).ConfigureAwait(false);
                if (response.IsSuccess)
                {
                    _ = await _subscribeService.InsertInvoiceLog(response.Data.InvoiceId);
                    return Redirect(response.Data.PaymentURL);
                }
                else
                {
                        var errors = "";
                        if (response.ValidationErrors != null)
                        {
                            foreach (var item in response.ValidationErrors)
                            {
                                errors += $" {item.Name} : {item.Error}   ||||||";
                            }
                        }
                        await _subscribeService.InsertError(response.Message,
                            $"Response State is :{response.IsSuccess} ||Errors :{response.ValidationErrors} |||| response Message : {response.Message}");
                        return View("ErrorPayment");
                }
            }
            return View("ErrorPayment");
        }


        [AllowAnonymous]
        [Route("~/ErrorPayment")]
        public IActionResult ErrorPayment()
        {
            return View();
        }

        [Route("~/CompletePayment")]
        public async Task<IActionResult> CompletePayment(string paymentId,bool isPaidFromWallet = false, PaymentViewModel paymentViewModel=null)
        {
            try
            
            {
                if(isPaidFromWallet == false)
                {
                    var message = await _paymentService.LogTransaction(new GetPaymentStatusRequest
                    {
                        Key = paymentId,
                        KeyType = "paymentId"
                    }).ConfigureAwait(false);
                    var response = JsonConvert.DeserializeObject<GenericResponse<GetPaymentStatusResponse>>(message);
                    if (response.IsSuccess)
                    {
                        if (response.Data.InvoiceStatus.ToLower() != "canceled")
                        {
                            var subscribeResult = new HttpResponseMessage();
                            var computedFiled = response.Data.UserDefinedField.Split(",", StringSplitOptions.RemoveEmptyEntries);
                            switch (computedFiled[0])
                            {
                                case string transaction when int.Parse(transaction) == (int)TransactionType.Course:
                                    subscribeResult = await _subscribeService.SubscribeCourse(message, !string.IsNullOrEmpty(response.Data.CustomerReference) ? long.Parse(response.Data.CustomerReference) : 0);
                                    break;

                                case string transaction when int.Parse(transaction) == (int)TransactionType.Live:
                                    subscribeResult = await _subscribeService.SubscribeLive(message, !string.IsNullOrEmpty(response.Data.CustomerReference) ? long.Parse(response.Data.CustomerReference) : 0);
                                    break;

                                case string transaction when int.Parse(transaction) == (int)TransactionType.Track:

TolabPortal/TolabPortal/Views/Shared/Components/MyFatoorahPayment/MyFatoorahPaymentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TolabPortal.DataAccess.Models.Payment;

namespace TolabPortal.Views.Shared.Components.MyFatoorahPayment
{
    public class MyFatoorahPaymentViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PayVm payViewmodel)
        {
            return View("Default", payViewmodel);
        }
    }

     
}

TolabPortal/TolabPortal/Views/Shared/Components/StudentTreeView/StudentTreeViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TolabPortal.DataAccess.Models;
using TolabPortal.ViewModels;

namespace TolabPortal.Views.Shared.Components.StudentTreeView
{
    public class StudentTreeViewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(List<Section> vm)
        {
            return View("Default", vm);
        }
    }

     
}

TolabPortal/TolabPortal/Views/Shared/Components/MyFatoorahPayment/Default.cshtml
@model PayVm
<a   href="#" class="btn theme-btn @Model.CssClassName" data-toggle="modal" data-target="#paymentModal-@Model.TransactionId" title="Pay Now" >اشترك</a>
 

 <!-- Modal -->
<div class="modal fade modal-container" id="paymentModal-@Model.TransactionId" tabindex="-1" role="dialog" aria-labelledby="paymentModalTitle"  aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-gray">
                <div class="pr-2">
                    <h5 class="modal-title fs-19 lh-24 txtbold" id="paymentModalTitle">اختر طريقة الدفع</h5>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="la la-times"></span>
                </button>
            </div><!-- end modal-header -->
            <div class="modal-body">
                <form asp-action="InitiatePayment" asp-controller="MyFatoorahPayment" method="post">
                    @Html.HiddenFor(a => a.TransactionId)
                    @Html.HiddenFor(a => a.InvoiceAmount)
                    @Html.HiddenFor(a => a.TransactionType)
                    @Html.HiddenFor(a => a.ReturnRoute)
                    @Html.HiddenFor(a => a.Balance)
                    <div class="input-box">
                        <div class="col-lg-12 responsive-column-half" style="display:none;">
                            <div class="custom-control custom-radio mb-3 ml-0 pl-0">
                                <input type="radio" class="custom-control-input" checked id="walletpay" asp-for="PaymentMethodId" value="1">
                                <label class="custom-control-label custom--control-label custom--control-label-boxed noshadbord" for="walletpay">
                                     <span class="font-weight-semi-bold text-black d-block">
                                        الدفع من رصيد المحفظة 
                                    </span>
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-12 responsive-column-half">
                            <div class="custom-control custom-radio mb-3 ml-0 pl-0">
                                <input type="radio" class="custom-control-input" id="evisapay" asp-for="PaymentMethodId" value="2" checked="checked" >
                                <label class="custom-control-label custom--control-label custom--control-label-boxed noshadbord" for="evisapay">
                                    <span class="font-weight-semi-bold text-black d-block">
                                        الدفع الالكترونى (فيزا/ماستر كارد)
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>


                    <div class="btn-box text-right pt-2">
                        <button type="button" class="btn font-weight-medium mr-3" data-dismiss="modal">الغاء</button>
                        <button type="submit" class="btn theme-btn theme-btn-sm lh-30">ادفع الان <i class="la la-arrow-right icon ml-1"></i></button>
                    </div>
                </form>
            </div><!-- end modal-body -->
        </div><!-- end modal-content -->
    </div><!-- end modal-dialog -->
</div><!-- end modal -->
<!-- Modal -->